import type { Metadata } from "next";

import { Readex_Pro } from "next/font/google";

import "./globals.css";
import "../public/assets/css/dark-theme.css";
import "../public/assets/css/remixicon.css";
import "../public/assets/css/fancybox.css";
import "../public/assets/css/animate.css";
import "../public/assets/css/aos.css";
import "../public/assets/css/slick-theme.css";
import "../public/assets/css/style.css";
import "../public/assets/css/responsive.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "boxicons/css/boxicons.min.css";
import "aos/dist/aos.css";
import "owl.carousel/dist/assets/owl.carousel.css";
import "owl.carousel/dist/assets/owl.theme.default.css";
import Layout from "@/components/Layout";
import WhatsAppButton from "@/components/WhatsAppButton";

const readexPro = Readex_Pro({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Choose required font weights
  variable: "--font-readex-pro", // Optional CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Add favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={readexPro.variable}>
      <body>
        <Layout>
          {children}
          <WhatsAppButton />
        </Layout>
      </body>
    </html>
  );
}
