import BlogPage from "./blogPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  metadataBase: new URL("https://www.tapovanswisscampsofficial.com"),
  title:
    "Rishikesh Adventure Blogs - Tapovan Swiss Camps | Best Camping & Adventure Guides 2025",
  description:
    "Discover expert travel guides for Rishikesh camping, rafting, bungee jumping, and bike rentals. Get insider tips, safety guides, and booking information from Tapovan Swiss Camps - Rishikesh's #1 adventure destination.",
  keywords: [
    "Rishikesh blogs",
    "camping in rishikesh blogs",
    "rafting in rishikesh blogs",
    "bungee jumping in rishikesh blogs",
    "bike rent in rishikesh blog",
    "rafting in rishikesh",
    "rafting guide",
    "bungee jumping Rishikesh",
    "bike rental Rishikesh",
    "adventure travel tips",
    "Tapovan Swiss Camps blog",
    "camping in rishikesh",
    "camping in rishikesh tapovan",
    "Rishikesh camping",
    "rishikesh camping and rafting",
    "riverside camping in rishikesh",
    "best camping in rishikesh",
    "best camp in tapovan, rishikesh",
    "rishikesh camping package",
    "rishikesh camping packages",
    "rishikesh camping resort",
    "rishikesh camping places",
    "rishikesh camping price per person",
    "camp brook",
    "luxury camping in rishikesh reviews",
    "luxury camping in rishikesh",
    "camping in rishikesh price",
    "shivpuri rishikesh camping",
    "camping in rishikesh shivpuri",
    "bonfire rishikesh camping",
    "luxury camping in rishikesh photos",
    "camping in rishikesh near ganga",
    "camping in rishikesh near river",
    "best camps in rishikesh near ganga",
    "rishikesh river side camping price",
    "camping sites in rishikesh",
    "rafting & camping in rishikesh",
    "rishikesh camping and rafting",
    "rishikesh camping price for couple",
    "rishikesh camping price for family",
    "cheapest camping in rishikesh",
    "Luxury AC tents Rishikesh",
    "Luxury Cooler tents Rishikesh",
    "Swiss camps Rishikesh",
    "rishikesh camping booking",
    "Riverside camp Rishikesh",
    "Tapovan Swiss Camps",
    "Camp near Ganga river",
    "Yoga retreat Rishikesh",
    "Family camping Rishikesh",
    "Couple camping Rishikesh",
    "Group camping Rishikesh",
    "Rishikesh adventure sports",
    "Best resort Rishikesh",
    "Ganga view camp Rishikesh",
    "Swimming pool camp Rishikesh",
    "Rishikesh travel guide",
    "Himalayan adventure blog",
    "Ganga river activities",
    "Uttarakhand tourism blog",
    "Adventure sports India",
    "White water rafting guide",
    "Bungee jumping safety tips",
    "Motorcycle rental Rishikesh",
    "Himalayan camping guide",
    "Spiritual tourism Rishikesh",
  ],
  authors: [{ name: "Tapovan Swiss Camps" }],
  creator: "Tapovan Swiss Camps",
  publisher: "Tapovan Swiss Camps",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: "https://www.tapovanswisscampsofficial.com/blogs",
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    title:
      "Rishikesh Adventure Blogs - Tapovan Swiss Camps | Best Camping & Adventure Guides 2025",
    description:
      "Discover expert travel guides for Rishikesh camping, rafting, bungee jumping, and bike rentals. Get insider tips, safety guides, and booking information from Tapovan Swiss Camps.",
    url: "https://www.tapovanswisscampsofficial.com/blogs",
    siteName: "Tapovan Swiss Camps",
    locale: "en_IN",
    type: "website",
    images: [
      {
        url: "https://www.tapovanswisscampsofficial.com/assets/img/blog/camping_rishikesh.webp",
        width: 1200,
        height: 630,
        alt: "Adventure activities and camping in Rishikesh - Tapovan Swiss Camps",
        type: "image/webp",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title:
      "Rishikesh Adventure Blogs - Tapovan Swiss Camps | Best Camping & Adventure Guides 2025",
    description:
      "Discover expert travel guides for Rishikesh camping, rafting, bungee jumping, and bike rentals. Get insider tips and booking information.",
    images: [
      "https://www.tapovanswisscampsofficial.com/assets/img/blog/camping_rishikesh.webp",
    ],
  },
};
const Blogs: React.FC = () => {
  return <BlogPage />;
};

export default Blogs;
